package com.example.workoutlogger.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6361FF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE2E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF050066)
val md_theme_light_secondary = Color(0xFF00A896)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF92F1E3)
val md_theme_light_onSecondaryContainer = Color(0xFF00211D)
val md_theme_light_tertiary = Color(0xFFFF8A65)
val md_theme_light_onTertiary = Color(0xFF3C1300)
val md_theme_light_tertiaryContainer = Color(0xFFFFCEBC)
val md_theme_light_onTertiaryContainer = Color(0xFF2B0A00)
val md_theme_light_background = Color(0xFFF7F6FF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE4E0F5)
val md_theme_light_onSurfaceVariant = Color(0xFF48454F)
val md_theme_light_outline = Color(0xFF807C89)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F6)
val md_theme_light_inverseSurface = Color(0xFF2F3036)

val md_theme_dark_primary = Color(0xFFC6C4FF)
val md_theme_dark_onPrimary = Color(0xFF1D198F)
val md_theme_dark_primaryContainer = Color(0xFF3F3CAA)
val md_theme_dark_onPrimaryContainer = Color(0xFFE2E7FF)
val md_theme_dark_secondary = Color(0xFF78D5C7)
val md_theme_dark_onSecondary = Color(0xFF003731)
val md_theme_dark_secondaryContainer = Color(0xFF005047)
val md_theme_dark_onSecondaryContainer = Color(0xFF92F1E3)
val md_theme_dark_tertiary = Color(0xFFFFB59C)
val md_theme_dark_onTertiary = Color(0xFF542200)
val md_theme_dark_tertiaryContainer = Color(0xFF7A3816)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFCEBC)
val md_theme_dark_background = Color(0xFF111218)
val md_theme_dark_onBackground = Color(0xFFE4E1ED)
val md_theme_dark_surface = Color(0xFF1A1B21)
val md_theme_dark_onSurface = Color(0xFFE4E1ED)
val md_theme_dark_surfaceVariant = Color(0xFF494458)
val md_theme_dark_onSurfaceVariant = Color(0xFFCCC4DA)
val md_theme_dark_outline = Color(0xFF958FA7)
val md_theme_dark_inverseOnSurface = Color(0xFF282931)
val md_theme_dark_inverseSurface = Color(0xFFF0EFF5)

val playful_gradient_start = Color(0xFFB4C3FF)
val playful_gradient_end = Color(0xFFB7F3E6)
