package com.example.workoutlogger.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00C853)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCFFCD7)
val md_theme_light_onPrimaryContainer = Color(0xFF003514)
val md_theme_light_secondary = Color(0xFF111111)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF1F1F1)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1C1C)
val md_theme_light_tertiary = Color(0xFF00E676)
val md_theme_light_onTertiary = Color(0xFF00210C)
val md_theme_light_tertiaryContainer = Color(0xFFB2FFD5)
val md_theme_light_onTertiaryContainer = Color(0xFF003919)
val md_theme_light_background = Color(0xFFFBFBFB)
val md_theme_light_onBackground = Color(0xFF090909)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF090909)
val md_theme_light_surfaceVariant = Color(0xFFE7E7E7)
val md_theme_light_onSurfaceVariant = Color(0xFF393939)
val md_theme_light_outline = Color(0xFFB5B5B5)
val md_theme_light_inverseOnSurface = Color(0xFFF4F4F4)
val md_theme_light_inverseSurface = Color(0xFF151515)

val md_theme_dark_primary = Color(0xFF00E676)
val md_theme_dark_onPrimary = Color(0xFF00320F)
val md_theme_dark_primaryContainer = Color(0xFF005427)
val md_theme_dark_onPrimaryContainer = Color(0xFFB9FFD0)
val md_theme_dark_secondary = Color(0xFFF2F2F2)
val md_theme_dark_onSecondary = Color(0xFF111111)
val md_theme_dark_secondaryContainer = Color(0xFF1E1E1E)
val md_theme_dark_onSecondaryContainer = Color(0xFFF2F2F2)
val md_theme_dark_tertiary = Color(0xFF00C853)
val md_theme_dark_onTertiary = Color(0xFF00240C)
val md_theme_dark_tertiaryContainer = Color(0xFF004425)
val md_theme_dark_onTertiaryContainer = Color(0xFFB2F5C9)
val md_theme_dark_background = Color(0xFF050505)
val md_theme_dark_onBackground = Color(0xFFF5F5F5)
val md_theme_dark_surface = Color(0xFF0E0E0E)
val md_theme_dark_onSurface = Color(0xFFF5F5F5)
val md_theme_dark_surfaceVariant = Color(0xFF222222)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C4C4)
val md_theme_dark_outline = Color(0xFF5A5A5A)
val md_theme_dark_inverseOnSurface = Color(0xFF090909)
val md_theme_dark_inverseSurface = Color(0xFFF0FFF6)

val playful_gradient_start = Color(0xFF021109)
val playful_gradient_end = Color(0xFFE3FFE9)
